#include "DataFormats/HGCalReco/interface/HGCalSoAClustersHostCollection.h"
#include "DataFormats/HGCalReco/interface/HGCalSoARecHitsExtraHostCollection.h"
#include "DataFormats/HGCalReco/interface/HGCalSoARecHitsHostCollection.h"
#include "DataFormats/HGCalReco/interface/alpaka/HGCalSoAClustersDeviceCollection.h"
#include "DataFormats/HGCalReco/interface/alpaka/HGCalSoARecHitsExtraDeviceCollection.h"
#include "DataFormats/HGCalReco/interface/alpaka/HGCalSoARecHitsDeviceCollection.h"
#include "HeterogeneousCore/TrivialSerialisation/interface/alpaka/SerialiserFactoryDevice.h"

DEFINE_TRIVIAL_SERIALISER_PLUGIN_HOST_DEVICE(HGCalSoAClustersHostCollection, HGCalSoAClustersDeviceCollection);
DEFINE_TRIVIAL_SERIALISER_PLUGIN_HOST_DEVICE(HGCalSoARecHitsExtraHostCollection, HGCalSoARecHitsExtraDeviceCollection);
DEFINE_TRIVIAL_SERIALISER_PLUGIN_HOST_DEVICE(HGCalSoARecHitsHostCollection, HGCalSoARecHitsDeviceCollection);
